### ISSUE TITLE
tuples dont get printed

### ISSUE THREAD

**Issue by ammarbinfaisal** [ammarbinfaisal/sahl#60]
a segfault :skull_and_crossbones:

**Comment by abooishaaq** [comment]
i didnt paste the code 🤦

**Comment by ammarbinfaisal** [comment]
doesnt working in native so that should be fixed. But iirc this error was related to bytecode vm

**Comment by ammarbinfaisal** [comment]
https://github.com/ammarbinfaisal/sahl/commit/f77b0a38b28b2279f17d9281da5c51d37f2e3f4a fixes tuple handling
